name: SonarCloud

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Install dependencies
        run: dotnet restore --runtime win

      - name: Build Solution
        run: |
          msbuild AppSec.sln /p:Configuration=Release /p:RuntimeIdentifiers=win

      - name: Run SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          projectKey: 'your-project-key'
          organization: 'your-organization'
          token: ${{ secrets.SONAR_TOKEN }}

      - name: End Analysis
        run: dotnet-sonarscanner end
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
