name: SonarCloud

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Install dependencies
        run: dotnet restore --runtime win

      - name: Build Solution
        run: |
          msbuild AppSec.sln /p:Configuration=Release /p:RuntimeIdentifiers=win

      - name: Run SonarCloud Analysis - Begin
        run: dotnet sonarscanner begin /k:"AkashdeepQA_AppSec" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Run Tests
        run: msbuild YourSolution.sln /t:Test /p:Configuration=Release

      - name: Run SonarCloud Analysis - End
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
